export type NumericalCalibrationOptionId = "A" | "B" | "C" | "D";

export type NumericalCalibrationDiagram =
  | { kind: "composite_area"; outerWidthM: number; outerHeightM: number; cutoutWidthM: number; cutoutHeightM: number }
  | { kind: "rectangular_tank"; lengthM: number; widthM: number; heightM: number }
  | { kind: "plan_scale"; planDistanceCm: number; scaleDenominator: number }
  | { kind: "map_grid_route"; blocksEast: number; blocksNorth: number; metresPerBlock: number }
  | { kind: "bar_chart"; categories: { label: string; value: number }[] }
  | { kind: "line_graph"; points: { minute: number; value: number }[]; yLabel: string }
  | { kind: "two_way_table"; rowLabels: [string, string]; columnLabels: [string, string]; values: [[number, number], [number, number]] };

export type NumericalCalibrationPilotItem = {
  questionId: string;
  blueprintId: `NUMERICAL-${string}`;
  familyId: string;
  archetype: string;
  difficulty: "foundation" | "applied" | "stretch";
  reasoningSteps: number;
  targetTimeRangeSec: { minSec: number; maxSec: number };
  stem: string;
  responseFormat?: "mcq" | "numeric_entry" | "true_false";
  options: { optionId: NumericalCalibrationOptionId; text: string }[];
  correctOptionId?: NumericalCalibrationOptionId;
  numericAnswer?: { value: number; tolerance: number; unitLabel?: string };
  explanation: string;
  misconceptionTags: Partial<Record<NumericalCalibrationOptionId, string>>;
  diagram?: NumericalCalibrationDiagram;
};

export const NUMERICAL_CALIBRATION_PILOT_VERSION = "APTESTA_NUMERICAL_CAL_V0_11_2026_08";

export const numericalCalibrationCoreItems: NumericalCalibrationPilotItem[] = [
  {
    questionId: "NUM-CAL-01",
    blueprintId: "NUMERICAL-01",
    familyId: "mental_arithmetic_two_step_v1",
    archetype: "mental_arithmetic_two_step",
    difficulty: "foundation",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 35, maxSec: 45 },
    stem: "What is 38 × 4 − 27?",
    options: [
      { optionId: "A", text: "98" },
      { optionId: "B", text: "125" },
      { optionId: "C", text: "145" },
      { optionId: "D", text: "179" },
    ],
    correctOptionId: "B",
    explanation: "38 × 4 = 152, then 152 − 27 = 125.",
    misconceptionTags: { A: "subtracted_before_multiplying", B: "correct", C: "subtraction_error", D: "added_instead_of_subtracted" },
  },
  {
    questionId: "NUM-CAL-02",
    blueprintId: "NUMERICAL-02",
    familyId: "numeric_estimation_v1",
    archetype: "numeric_estimation",
    difficulty: "foundation",
    reasoningSteps: 1,
    targetTimeRangeSec: { minSec: 30, maxSec: 40 },
    stem: "Which is the closest estimate for 398 × 21?",
    options: [
      { optionId: "A", text: "800" },
      { optionId: "B", text: "4,000" },
      { optionId: "C", text: "8,000" },
      { optionId: "D", text: "12,000" },
    ],
    correctOptionId: "C",
    explanation: "Round 398 to about 400 and 21 to about 20. Then 400 × 20 ≈ 8,000.",
    misconceptionTags: { A: "place_value_error", B: "halved_product", C: "correct", D: "overestimated_product" },
  },
  {
    questionId: "NUM-CAL-03",
    blueprintId: "NUMERICAL-03",
    familyId: "percentage_of_quantity_v1",
    archetype: "percentage_of_quantity",
    difficulty: "foundation",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 40, maxSec: 50 },
    stem: "A tank contains 240 L. What is 12.5% of this amount?",
    options: [
      { optionId: "A", text: "24 L" },
      { optionId: "B", text: "36 L" },
      { optionId: "C", text: "48 L" },
      { optionId: "D", text: "30 L" },
    ],
    correctOptionId: "D",
    explanation: "12.5% is one eighth. 240 ÷ 8 = 30 L.",
    misconceptionTags: { A: "used_ten_percent", B: "used_fifteen_percent", C: "used_twenty_percent", D: "correct" },
  },
  {
    questionId: "NUM-CAL-04",
    blueprintId: "NUMERICAL-04",
    familyId: "percentage_change_v1",
    archetype: "percentage_change",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 45, maxSec: 60 },
    stem: "A reading increases from 80 to 92. What is the percentage increase?",
    options: [
      { optionId: "A", text: "15%" },
      { optionId: "B", text: "12%" },
      { optionId: "C", text: "13%" },
      { optionId: "D", text: "20%" },
    ],
    correctOptionId: "A",
    explanation: "The increase is 12. Divide by the original value: 12 ÷ 80 = 0.15 = 15%.",
    misconceptionTags: { A: "correct", B: "used_absolute_change_as_percent", C: "divided_by_final_value", D: "denominator_error" },
  },
  {
    questionId: "NUM-CAL-05",
    blueprintId: "NUMERICAL-05",
    familyId: "ratio_sharing_v1",
    archetype: "ratio_sharing",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 45, maxSec: 60 },
    stem: "A total of 600 units is divided in the ratio 2 : 3 : 5. How many units are in the middle share?",
    options: [
      { optionId: "A", text: "120" },
      { optionId: "B", text: "200" },
      { optionId: "C", text: "180" },
      { optionId: "D", text: "300" },
    ],
    correctOptionId: "C",
    explanation: "There are 10 ratio parts in total. Each part is 600 ÷ 10 = 60. The middle share is 3 × 60 = 180.",
    misconceptionTags: { A: "selected_two_part_share", B: "divided_by_three", C: "correct", D: "selected_five_part_share" },
  },
  {
    questionId: "NUM-CAL-06",
    blueprintId: "NUMERICAL-06",
    familyId: "direct_rate_v1",
    archetype: "direct_rate",
    difficulty: "foundation",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 40, maxSec: 50 },
    stem: "A vehicle travels 150 km in 2.5 hours. What is its average speed?",
    options: [
      { optionId: "A", text: "60 km/h" },
      { optionId: "B", text: "50 km/h" },
      { optionId: "C", text: "75 km/h" },
      { optionId: "D", text: "375 km/h" },
    ],
    correctOptionId: "A",
    explanation: "Average speed = distance ÷ time = 150 ÷ 2.5 = 60 km/h.",
    misconceptionTags: { A: "correct", B: "division_error", C: "treated_2_5_as_2", D: "multiplied_instead_of_divided" },
  },
  {
    questionId: "NUM-CAL-07",
    blueprintId: "NUMERICAL-07",
    familyId: "inverse_work_rate_v1",
    archetype: "inverse_work_rate",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    stem: "Six identical pumps can empty a reservoir in 8 hours. At the same constant rate per pump, how long would 12 pumps take?",
    options: [
      { optionId: "A", text: "2 hours" },
      { optionId: "B", text: "8 hours" },
      { optionId: "C", text: "16 hours" },
      { optionId: "D", text: "4 hours" },
    ],
    correctOptionId: "D",
    explanation: "Doubling the number of identical pumps halves the time for the same fixed job: 8 ÷ 2 = 4 hours.",
    misconceptionTags: { A: "over_halved_time", B: "ignored_inverse_relationship", C: "used_direct_relationship", D: "correct" },
  },
  {
    questionId: "NUM-CAL-08",
    blueprintId: "NUMERICAL-08",
    familyId: "missing_value_average_v1",
    archetype: "missing_value_average",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 45, maxSec: 55 },
    stem: "Five measurements have an average of 18. Four of the measurements are 12, 16, 19 and 21. What is the fifth measurement?",
    options: [
      { optionId: "A", text: "18" },
      { optionId: "B", text: "22" },
      { optionId: "C", text: "20" },
      { optionId: "D", text: "24" },
    ],
    correctOptionId: "B",
    explanation: "The five values must total 5 × 18 = 90. The four known values total 68, so the missing value is 90 − 68 = 22.",
    misconceptionTags: { A: "used_average_as_missing_value", B: "correct", C: "addition_error", D: "subtraction_error" },
  },
];

export const numericalCalibrationAppliedDataItems: NumericalCalibrationPilotItem[] = [
  {
    questionId: "NUM-CAL-09",
    blueprintId: "NUMERICAL-09",
    familyId: "discount_tax_unit_price_v1",
    archetype: "discount_tax_unit_price",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    stem: "A tool is marked at $240. It is discounted by 15%, then 10% GST is added to the discounted price. What is the final price?",
    options: [
      { optionId: "A", text: "$204.00" },
      { optionId: "B", text: "$224.40" },
      { optionId: "C", text: "$228.00" },
      { optionId: "D", text: "$249.60" },
    ],
    correctOptionId: "B",
    explanation: "After the 15% discount: $240 × 0.85 = $204. Adding 10% GST gives $204 × 1.10 = $224.40.",
    misconceptionTags: { A: "stopped_after_discount", B: "correct", C: "subtracted_discount_then_added_ten_percent_of_original", D: "added_gst_before_discount" },
  },
  {
    questionId: "NUM-CAL-10",
    blueprintId: "NUMERICAL-10",
    familyId: "measurement_conversion_v1",
    archetype: "measurement_conversion",
    difficulty: "foundation",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 40, maxSec: 50 },
    stem: "A hose is 2.4 m long and an extension adds 65 cm. What is the total length in centimetres?",
    options: [
      { optionId: "A", text: "89 cm" },
      { optionId: "B", text: "240 cm" },
      { optionId: "C", text: "305 cm" },
      { optionId: "D", text: "6,500 cm" },
    ],
    correctOptionId: "C",
    explanation: "2.4 m = 240 cm. Then 240 + 65 = 305 cm.",
    misconceptionTags: { A: "added_without_unit_conversion", B: "ignored_extension", C: "correct", D: "conversion_factor_error" },
  },
  {
    questionId: "NUM-CAL-11",
    blueprintId: "NUMERICAL-11",
    familyId: "composite_area_v1",
    archetype: "composite_area",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    stem: "A rectangular floor is 8 m by 6 m. A 2 m by 3 m service bay in one corner is excluded. What usable floor area remains?",
    diagram: { kind: "composite_area", outerWidthM: 8, outerHeightM: 6, cutoutWidthM: 2, cutoutHeightM: 3 },
    options: [
      { optionId: "A", text: "42 m²" },
      { optionId: "B", text: "48 m²" },
      { optionId: "C", text: "36 m²" },
      { optionId: "D", text: "30 m²" },
    ],
    correctOptionId: "A",
    explanation: "Whole area = 8 × 6 = 48 m². Excluded bay = 2 × 3 = 6 m². Usable area = 48 − 6 = 42 m².",
    misconceptionTags: { A: "correct", B: "ignored_excluded_area", C: "subtracted_wrong_dimension", D: "used_perimeter_like_operation" },
  },
  {
    questionId: "NUM-CAL-12",
    blueprintId: "NUMERICAL-12",
    familyId: "rectangular_volume_v1",
    archetype: "rectangular_volume",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    stem: "A rectangular tank measures 1.2 m × 0.8 m × 0.5 m internally. Approximately how many litres does it hold when full?",
    diagram: { kind: "rectangular_tank", lengthM: 1.2, widthM: 0.8, heightM: 0.5 },
    options: [
      { optionId: "A", text: "48 L" },
      { optionId: "B", text: "480 L" },
      { optionId: "C", text: "4,800 L" },
      { optionId: "D", text: "960 L" },
    ],
    correctOptionId: "B",
    explanation: "Volume = 1.2 × 0.8 × 0.5 = 0.48 m³. Since 1 m³ = 1,000 L, the tank holds 480 L.",
    misconceptionTags: { A: "litre_conversion_divide_by_ten", B: "correct", C: "litre_conversion_times_ten", D: "failed_to_multiply_height" },
  },
  {
    questionId: "NUM-CAL-13",
    blueprintId: "NUMERICAL-13",
    familyId: "plan_scale_distance_v1",
    archetype: "plan_scale_distance",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 55, maxSec: 70 },
    stem: "On a plan drawn at 1 : 500, a corridor measures 7.2 cm. What is the real corridor length?",
    diagram: { kind: "plan_scale", planDistanceCm: 7.2, scaleDenominator: 500 },
    options: [
      { optionId: "A", text: "3.6 m" },
      { optionId: "B", text: "36 m" },
      { optionId: "C", text: "360 m" },
      { optionId: "D", text: "7.2 m" },
    ],
    correctOptionId: "B",
    explanation: "7.2 cm × 500 = 3,600 cm = 36 m.",
    misconceptionTags: { A: "conversion_factor_too_small", B: "correct", C: "centimetres_to_metres_error", D: "ignored_scale" },
  },
  {
    questionId: "NUM-CAL-14",
    blueprintId: "NUMERICAL-14",
    familyId: "map_grid_distance_v1",
    archetype: "map_grid_distance",
    difficulty: "applied",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    stem: "The marked route travels 3 grid blocks east and then 4 grid blocks north. Each grid block represents 250 m. What distance is travelled along the marked route?",
    diagram: { kind: "map_grid_route", blocksEast: 3, blocksNorth: 4, metresPerBlock: 250 },
    options: [
      { optionId: "A", text: "1,000 m" },
      { optionId: "B", text: "1,250 m" },
      { optionId: "C", text: "1,750 m" },
      { optionId: "D", text: "2,500 m" },
    ],
    correctOptionId: "C",
    explanation: "The route covers 3 + 4 = 7 blocks. At 250 m per block, 7 × 250 = 1,750 m.",
    misconceptionTags: { A: "used_four_blocks_only", B: "used_straight_line_three_four_five", C: "correct", D: "multiplied_ten_blocks" },
  },
  {
    questionId: "NUM-CAL-15",
    blueprintId: "NUMERICAL-15",
    familyId: "bar_chart_comparison_v1",
    archetype: "bar_chart_comparison",
    difficulty: "applied",
    reasoningSteps: 3,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    stem: "The chart shows completed inspections for three teams. Team B completed what percentage more inspections than Team C?",
    diagram: { kind: "bar_chart", categories: [{ label: "A", value: 40 }, { label: "B", value: 60 }, { label: "C", value: 48 }] },
    options: [
      { optionId: "A", text: "12%" },
      { optionId: "B", text: "20%" },
      { optionId: "C", text: "25%" },
      { optionId: "D", text: "80%" },
    ],
    correctOptionId: "C",
    explanation: "Team B exceeds Team C by 12. Relative to Team C, 12 ÷ 48 = 0.25 = 25%.",
    misconceptionTags: { A: "used_absolute_difference_as_percent", B: "divided_by_team_b", C: "correct", D: "used_c_as_percent_of_b" },
  },
  {
    questionId: "NUM-CAL-16",
    blueprintId: "NUMERICAL-16",
    familyId: "line_graph_rate_v1",
    archetype: "line_graph_rate",
    difficulty: "applied",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    stem: "Between 10 and 20 minutes, what is the average rate of increase shown on the graph?",
    diagram: { kind: "line_graph", points: [{ minute: 0, value: 100 }, { minute: 10, value: 140 }, { minute: 20, value: 180 }], yLabel: "Volume (L)" },
    options: [
      { optionId: "A", text: "2 L/min" },
      { optionId: "B", text: "4 L/min" },
      { optionId: "C", text: "8 L/min" },
      { optionId: "D", text: "40 L/min" },
    ],
    correctOptionId: "B",
    explanation: "The value rises from 140 L to 180 L: an increase of 40 L over 10 minutes. 40 ÷ 10 = 4 L/min.",
    misconceptionTags: { A: "halved_rate", B: "correct", C: "divided_by_five", D: "used_change_without_dividing_by_time" },
  },
];

export const numericalCalibrationFinalFormatItems: NumericalCalibrationPilotItem[] = [
  {
    questionId: "NUM-CAL-17",
    blueprintId: "NUMERICAL-17",
    familyId: "two_way_table_v1",
    archetype: "two_way_table",
    difficulty: "applied",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    stem: "The table shows training completion by shift. Of all staff who have NOT completed the training, what percentage work the night shift?",
    diagram: { kind: "two_way_table", rowLabels: ["Day shift", "Night shift"], columnLabels: ["Completed", "Not completed"], values: [[36, 9], [24, 6]] },
    options: [
      { optionId: "A", text: "20%" },
      { optionId: "B", text: "30%" },
      { optionId: "C", text: "40%" },
      { optionId: "D", text: "60%" },
    ],
    correctOptionId: "C",
    explanation: "There are 9 + 6 = 15 staff who have not completed the training. Of those, 6 are on night shift. 6 ÷ 15 = 0.40 = 40%.",
    misconceptionTags: { A: "used_night_noncomplete_over_all_night", B: "used_six_over_twenty", C: "correct", D: "used_night_completed_ratio" },
  },
  {
    questionId: "NUM-CAL-18",
    blueprintId: "NUMERICAL-18",
    familyId: "simple_probability_v1",
    archetype: "simple_probability",
    difficulty: "applied",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 45, maxSec: 60 },
    stem: "A bag contains 5 red markers, 3 blue markers and 2 green markers. One marker is chosen at random. What is the probability that it is blue?",
    options: [
      { optionId: "A", text: "0.2" },
      { optionId: "B", text: "0.3" },
      { optionId: "C", text: "0.5" },
      { optionId: "D", text: "0.7" },
    ],
    correctOptionId: "B",
    explanation: "There are 10 markers in total and 3 are blue, so the probability is 3 ÷ 10 = 0.3.",
    misconceptionTags: { A: "used_green_count", B: "correct", C: "used_red_count", D: "used_nonblue_count" },
  },
  {
    questionId: "NUM-CAL-19",
    blueprintId: "NUMERICAL-19",
    familyId: "numeric_entry_area_rate_v1",
    archetype: "numeric_entry_area_rate",
    difficulty: "applied",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 50, maxSec: 65 },
    responseFormat: "numeric_entry",
    stem: "A pump transfers 840 litres in 7 minutes at a constant rate. Enter the average flow rate in litres per minute.",
    options: [],
    numericAnswer: { value: 120, tolerance: 0.001, unitLabel: "L/min" },
    explanation: "Average flow rate = volume ÷ time = 840 ÷ 7 = 120 L/min.",
    misconceptionTags: {},
  },
  {
    questionId: "NUM-CAL-20",
    blueprintId: "NUMERICAL-20",
    familyId: "data_claim_true_false_v1",
    archetype: "data_claim_true_false",
    difficulty: "applied",
    reasoningSteps: 2,
    targetTimeRangeSec: { minSec: 45, maxSec: 60 },
    responseFormat: "true_false",
    stem: "The table compares assessment outcomes at two sites. Claim: Site B has a higher pass rate than Site A. Is the claim true or false?",
    diagram: { kind: "two_way_table", rowLabels: ["Site A", "Site B"], columnLabels: ["Passed", "Not passed"], values: [[30, 10], [24, 6]] },
    options: [
      { optionId: "A", text: "True" },
      { optionId: "B", text: "False" },
    ],
    correctOptionId: "A",
    explanation: "Site A pass rate = 30 ÷ 40 = 75%. Site B pass rate = 24 ÷ 30 = 80%. Site B is higher, so the claim is true.",
    misconceptionTags: { A: "correct", B: "compared_pass_counts_instead_of_rates" },
  },
];

// Kept for compatibility with v0.9 code paths and existing exports.
export const numericalCalibrationPilotItems = numericalCalibrationCoreItems;
export const numericalCalibrationAllItems = [...numericalCalibrationCoreItems, ...numericalCalibrationAppliedDataItems, ...numericalCalibrationFinalFormatItems];
